### ISSUE TITLE
Can't boot up Vagrant 

### ISSUE THREAD

**Issue by davidsf** [lucee/lucee-dockerfiles#15]
I have vagrant 1.7.4, installed vagrant workbench. 

vagrant up dockerhost works ok
with "vagrant up lucee45" produces the error:

```
There are errors in the configuration of this machine. Please fix
the following errors and try again:

vm:
* A box must be specified.
```

How can't I fix it ? Thanks

**Comment by modius** [comment]
`vagrant up dockerhost` starts a project specific VM.  If you are running a VM defined in the parent folder (ie. like the Daemonite Workbench approach) Vagrant will attempt to start containers in that location by default.

The README is a little bit confusing, I've tried to make it a bit clearer.

If you have the [Daemon Vagrant Workbench](https://github.com/daemonite/workbench) approach in place you will have a `Vagrantfile` in the parent folder. You must start this parent Boot2Docker VM separately, for example:
```
$ cd ~/Workbench/
$ vagrant up
```
This will start a VM that can run containers from different projects, rather than having a separate VM per project.

Then to run one of the Lucee test containers you would try:
```
$ git clone git@github.com:lucee/lucee-dockerfiles.git
$ cd lucee-dockerfiles
$ vagrant up lucee45
```

If you do not have the parent `../Vagrantfile` and instead want to get up and running with a VM that is unique to the `lucee-dockerfiles` project you can use the following commands:
```
$ cd ~/myluceetests
$ git clone git@github.com:lucee/lucee-dockerfiles.git
$ cd lucee-dockerfiles
$ vagrant up dockerhost
$ vagrant up lucee45
$ open http://192.168.56.100:8001
```

This approach will create a VM just for the `lucee-dockerfiles` project called **dockerhost** on **192.168.56.100** IP address. Note, it will not work if you have a `Vagrantfile` in the projects parent folder.
