### ISSUE TITLE
Hello World Instructions for lucee/lucee4:latest

### ISSUE THREAD

**Issue by jamiejackson** [lucee/lucee-dockerfiles#22]
Could you give instructions on how to run and access Hello World with `lucee/lucee4:latest`?

(I can't seem to access http://192.168.99.100:8888/, despite seeing Lucee's logs appearing to show the server starting up properly.)

Assume I've got the Docker tools ready to go, and have run other containers before.

**Comment by justincarter** [comment]
Assuming you are well past this point now :) Simply running Lucee 4 would have been something like;

`docker run -d -p 8888:8888 lucee/lucee4`

For real world usage, you would define your own `Dockerfile` and probably make use of `docker-compose` to store your local configuration rather than using command line.
