### ISSUE TITLE
add symlink to /Users/www/[project] in /var/www to access and serve local files

### ISSUE THREAD

**Issue by mattiLeBlanc** [lucee/lucee-dockerfiles#32]
Hi,

I am trying to serve local CFML files on my mac via the docker container.
I got so far as to mount the specific folder on my mac to a symlink within my docker images
```
docker run -it imagesname 	-v /Users/[username]/www/projectx:/code /bin/bash
```

So on the bash in the docker image I now have /code.
I then create a symlink `ln -s /code projectx` in my /var/www

When I then serve the image running tomcat whilst also mounting the the folder
```
	docker run -p 1337:8888 -v /Users/[username]/www/projectx:/code [imagename] catalina.sh run
```
I would expect to be able to access `http://localhost:1337/projectx`
Unfortunately it can't find that folder. Probably sinces Lucee doesn't recognises/indexes the the files on run time?

Is this possible?

The outcome I am look at is developing my Coldfusion app on my MAC while running Lucee+mysql on my docker container and having the source code locally so that I don't have to play with samba shares or other ways to be able to edit the coldfusion files in my IDE.

**Comment by modius** [comment]
@mattiLeBlanc these issues relate to the run time environment of your container, rather than the image itself. Rather than symlinks you probably should be looking at setting up an appropriate VOLUME for your container instance.

We find the following utility and lucee sample repo for useful:

- https://github.com/justincarter/docker-workbench
- https://github.com/modius/lucee-docker-workbench
