### ISSUE TITLE
Lucee 5.3

### ISSUE THREAD

**Issue by damien-git** [lucee/lucee-dockerfiles#49]
Lucee 5.3.1.95 has been released. What timeline should we expect for it to be integrated here ? Thanks.

**Comment by justincarter** [comment]
The latest builds are here in a new repository that will be announced soon;
https://hub.docker.com/r/lucee/lucee/tags

I would recommend trying the 5.3.1.97-SNAPSHOT if you rely on the MySQL driver and cfdbinfo as there have been some patches since 5.3.1.95.

The new repository has a build matrix that provides a lot more options than we could before. Be aware that the new defaults will be Tomcat 9.0 and Java 11, although there are still some Java 8 tagged images to ease the transition for those with upgrade issues.
