### ISSUE TITLE
Need a tag for 5.3.3.65

### ISSUE THREAD

**Issue by sbleon** [lucee/lucee-dockerfiles#59]
Hello! I'm hoping to test the newly-released (a few days ago) version 5.3.3.65, but I don't see a tag for it yet. Can someone please build it?

(I'm also curious to know if there's an automated build process for these images, or if that's an area that needs work.)

**Comment by justincarter** [comment]
The SNAPSHOT builds are indeed fully automated in Travis CI, however the RC, BETA and Release builds do require me to trigger them manually. The RC, BETA and Release builds usually happens about once per month at the most so it's not too much of a time burden (takes me 60 seconds to do that per manual trigger).

From the [Lucee Downloads](https://download.lucee.org/) page, the Release builds for 5.3.x are;
![image](https://user-images.githubusercontent.com/350221/74201459-01728100-4cbe-11ea-88ea-f03ab7b45831.png)

The 5.3.3.65 build that you're referring to seems to be a SNAPSHOT build;
![image](https://user-images.githubusercontent.com/350221/74201510-1f3fe600-4cbe-11ea-9543-011fdc8da68c.png)

You're right that there's no tagged image in Docker Hub matching that build number;
https://hub.docker.com/r/lucee/lucee/tags?page=1&name=5.3.3.65

It looks like when a release is done such as Release 5.3.3.62, any SNAPSHOT builds that are newer than the release don't get triggered which is why SNAPSHOT 5.3.3.65 doesn't exist. You can see in the Travis CI build history there is no matching build;
https://travis-ci.org/lucee/lucee-dockerfiles/builds

I'll have to dig in to that manually to try to work out why the build isn't triggered, but I'd say in general its should be fairly rare for new builds to happen after a release (unless it's also marked as a Release that supersedes the previous one, which is itself also rare). Also the fix that is in that build should be appearing in a newer 5.3.4.x or 5.3.5.x build if you're interested in trying those.

In the meantime I'll trigger a manual build for 5.3.3.5-SNAPSHOT.

**Comment by justincarter** [comment]
Build is now complete;

https://travis-ci.org/lucee/lucee-dockerfiles/builds/648684156
https://hub.docker.com/r/lucee/lucee/tags?page=1&name=5.3.3.65

**Comment by sbleon** [comment]
Thanks, Justin!
