### ISSUE TITLE
Add PATH_INFO to default NGINX conf

### ISSUE THREAD

**Issue by modius** [lucee/lucee-dockerfiles#6]
http://www.lucee.nl/post.cfm/enable-path-info-on-nginx-with-lucee-and-railo

**Comment by justincarter** [comment]
I've now added support for path_info style requests via nginx. This simple change works because the URL pattern is handled by Tomcat/Lucee (no need for `if` statements, headers or redirects in nginx configuration);
https://github.com/lucee/lucee-dockerfiles/commit/bc4608bfd10dc5bca510818730e53f6004d66c74#diff-6e3b94cc2962c9b71ad79693ede922cb

path_info style requests were already supported on `/index.cfm/*` for requests going via Tomcat;
https://github.com/lucee/lucee-dockerfiles/commit/1b51605d9baf98baf88c17ec7964cd8f2d2ae72d#diff-56ee1d34bebfd3885ff8f8a5fc3129f7R4643

If a pattern other than `/index.cfm/*` is required then the appropriate `<url-pattern>` must be added to Tomcat web.xml.

**Comment by wongrm** [comment]
> I've now added support for path_info style requests via nginx. This simple change works because the URL pattern is handled by Tomcat/Lucee (no need for `if` statements, headers or redirects in nginx configuration); [bc4608b#diff-6e3b94cc2962c9b71ad79693ede922cb](https://github.com/lucee/lucee-dockerfiles/commit/bc4608bfd10dc5bca510818730e53f6004d66c74#diff-6e3b94cc2962c9b71ad79693ede922cb)
> 
> path_info style requests were already supported on `/index.cfm/*` for requests going via Tomcat; [1b51605#diff-56ee1d34bebfd3885ff8f8a5fc3129f7R4643](https://github.com/lucee/lucee-dockerfiles/commit/1b51605d9baf98baf88c17ec7964cd8f2d2ae72d#diff-56ee1d34bebfd3885ff8f8a5fc3129f7R4643)
> 
> If a pattern other than `/index.cfm/*` is required then the appropriate `<url-pattern>` must be added to Tomcat web.xml.

Hi Justin,

So is what you're saying here that path_info should return a value after index.cfm with this patch.  I just created a container from the lucee:5.4 image and I'm getting no responses when trying to access URL in this form:

![Uploading image.png…]()


Thanks
